import pool from "../databases/database.js";


const mInicio = {
    inicializar: async () => {
        try{
            const result = await pool.query(`SELECT * FROM dbc.USERS`);
            console.log(result.rows);
            await pool.query(`INSERT INTO dbc.menu
                (mnu_category, mnu_name, mnu_description, mnu_price) VALUES
('Café y bebidas','Espresso','Solo o cortado: Una carga de nuestro café solo o con leche',35),
('Café y bebidas','Espresso doble (o doble cortado)','Dos carfas de nuestro cfé simple o con leche espumosa',44),
('Café y bebidas','Americano','Espresso largo con un poco de agua caliente',35),
('Café y bebidas','Latte','Tradicional café con leche',52),
('Café y bebidas','Capuccino','Leche espumada y espresso',52),
('Café y bebidas','Latte o capuccino + sabor','Agrega un toque de sabor. Elige de nuestra variedad.',65),
('Café y bebidas','Latte o capuccino + licor','Agrega un toque de licor. Elige de nuestra variedad.',110),
('Café y bebidas','Café Laberinto','Mismo concepto del latte, tres veces más grande',85),
('Café y bebidas','Café Laberinto + sabor','',99),
('Café y bebidas','Café Laberinto + licor','',149),
('Café y bebidas','Café irlandés','Nuestro espresso doble acompañado de whiskey y crema batida',169),
('Café y bebidas','Carajillo Laberinto','Nuestro espresso con leche, anís y brandy',169),
('Café y bebidas','Carajillo con licor 43','Nuestro espresso con licor de hierbas',169),
('Café y bebidas','Affogato','Gelato de vainilla "ahogado" en espresso',85),
('Café y bebidas','Chocolate','Chocolate caliente tradicional a base de leche o agua',65),
('Café y bebidas','Chocoespresso','Nuestro chocolate con una carga de espresso',79),
('Café y bebidas','Chocolate con rompope','Nuestro chocolate con una carga de rompope',65),
('Café y bebidas','Chocolate con licor','Nuestro chocolate con una carga de anís, brandy o whiskey',65),
('Café y bebidas','Infusión caliente','',52),
('Café y bebidas','Chai','Té negro y especias con leche y un toque dulce: original, manzana-canela o vainilla',73),
('Café y bebidas','Matcha','Té de hojas verdes, especias y un toque dulce',73),
('Café y bebidas','Frappé','Café espresso, huelo molido y un toque de sabor (16 oz)',90),
('Café y bebidas','Smoothie','Deliciosa pulpa de fruta con leche o agua y hielo molido en una extensa variedad de sabores (16 oz)',93),
('Café y bebidas','Refresco','',42),
('Café y bebidas','Felix','Bebida de agua mienral con mezcla de frutas, pregunta por los sabores',50),
('Café y bebidas','Botella de agua','',42),
('Café y bebidas','Vaso de leche','',42),
('Café y bebidas','Copa de vino de la casa (3 oz)','',99),
('Café y bebidas','Botella de vino de la casa','',390),
('Café y bebidas','Cerveza Minerva','Colonial, viena, Pale Ale, Stout',89),
('Café y bebidas','Cerveza Odin o Lágrimas Negras','Pregunta por nuestras cervezas de temporada',120),
('Café y bebidas','Digestivo','2 oz de whiskey, anís, tequila, brandy o crema irlandesa',165),
('Nuestras creaciones','Café dorado','Nuestro tradicional café con leche mezclado con revitalizante preparación de cúrcuma y especias',88),
('Nuestras creaciones','Café mazapán','Nuestro tradicional café con leche con mazapán de cacahuate',88),
('Nuestras creaciones','Café Jengibre','Nuestro tradicional café con leche con jengibre y especias',88),
('Nuestras creaciones','Leche dorada','Revitalizante preparación de cúrcuma y especias en leche caliente',73),
('Nuestras creaciones','Leche Mazapán','Leche con mazapán de cacahuate',73),
('Nuestras creaciones','Leche Jengibre','Leche con jengibre y especias',73),
('Nuestras creaciones','Manzanilla chai','Infusión de manzanilla con un toque de canela y leche espumada',73),
('Nuestras creaciones','Negro chai','Infusión de té negro con leche y especias',73),
('Nuestras creaciones','Nutellino','Espresso con un toque de nutella y crema batida',85),
('Nuestras creaciones','Cacahuatino','Espresso con un toque de crema de cacahuate y crema batida',85),
('De la cocina','Chapata','Pan chapata a la plancha con jitomate y espinacas: jamón de pavo y panela, jamón de pierna y manchego, tres quesos, Roast beef, jamón serrano o salami con queso',105),
('De la cocina','Sandwich','Sandwich a la plancha con jitomate y espinacas: jamón de pavo y panela, jamón de pierna y manchego, tres quesos, Roast beef, jamón serrano o salami con queso',76),
('De la cocina','Bagel','Bagel calientito y relleno de nuestros deliciosos ingredientes: atún, humus o jocoque',99),
('De la cocina','Bagel Salmón','',125),
('De la cocina','Quiché de jamón, queso y tocino','',99),
('De la cocina','Quiché de queso, espinaca y champiñones','',99),
('De la cocina','Lasagna','Deliiciosa porción del plato tradicional de la cocina italiana: láminas de pasta rellenas de salsa con carne, champiñones, espinacas y queso',119),
('De la cocina','Ensalada','Fresca ensalada individual aderezada con nuesra vinagreta, una opción muy salidable. Pregunta por nuestra variedad.',99),
('De la cocina','Plato de pitas','Nuestras deliciosas pitas acompañadas de humus o jocoque a tu elección',149),
('De la cocina','Yogurt con frutas y cereales','',72),
('De la cocina','Pastel rebanada','',72),
('De la cocina','Pastel a la modé','Nuestra rebanada de pastel con una bola de helado',119),
('De la cocina','Pastel San Sebastián','Clásico, blueberry, fresa, crema de cacahuate, galleta Biscoff, gallera Oreo, chocolate, o crema de cacahuate (pregunta por las opciones del día)',89),
('De la cocina','Galletas de la casa','',54),
('De la cocina','Alfajor','',72),
('De la cocina','Brownie a la modé','',69),
('De la cocina','Brownie a la modé','',99),
('De la cocina','Barras cereal','',40),
('De la cocina','Pieza de pan','',34),
('De la cocina','Dona','',34),
('De la cocina','Bola de helado','',40),
('Paquetes','Pan + Capuccino/Latte','',82),
('Paquetes','Pan + Americano','',68),
('Paquetes','Pastel + Capuccino/Latte','',119),
('Paquetes','Paste + Americano','',99),
('Paquetes','Bagel + Refresco/Agua','',135),
('Paquetes','Bagel + Capuccino/Latte','',146),
('Paquetes','Bagel + Americano','',130),
('Paquetes','Bagel salmón + Copa de vino','',211),
('Paquetes','Quiché + Refresco/agua','',143),
('Paquetes','Quiché + Capuccino/latte','',151),
('Paquetes','Quiché + Americano','',139),
('Paquetes','Quiché + Copa de vino','',185),
('Paquetes','Quiché + 2 copas de vino','',264),
('Paquetes','Plato de pitas + 2 copas de vino','',319),
('Paquetes','Galletas + Capuccino/latte','',99),
('Paquetes','Galletas + Americano','',81),
('Paquetes','Galletas + Té','',102),
('Paquetes','Yogurt + americano','',89),
('Paquetes','Sandwich + Refresco/Agua','',119),
('Paquetes','Chapata + Refresco/Agua','',143),
('Paquetes','Chapata + Capuccino/latte','',150),
('Paquetes','Chapata + Americano','',134),
('Paquetes','Chapata + Cerveza','',182),
('Paquetes','Chapata + Copa de vino','',197),
('Paquetes','Chapata + 2 copas de vino','',278),
('Paquetes','lasagna + 1 copa de vino','',207),
('Para llevar','Espresso','',36),
('Para llevar','Espresso doble','',45),
('Para llevar','Americano 12 oz','',48),
('Para llevar','Americano 16 oz','',52),
('Para llevar','Capuccino/Latte 12 oz','',67),
('Para llevar','Capucciono/latte 16 oz','',77),
('Para llevar','Capuccino/latte sabor 12 oz','',78),
('Para llevar','Capuccino/latte sabor 16 oz','',87),
('Para llevar','Capuccino/latte licor 12 oz','',120),
('Para llevar','Capuccino/latte licor 16 oz','',132),
('Para llevar','Chocolate 12 oz','',77),
('Para llevar','Chocolate 16 oz','',89),
('Para llevar','Chocolate con rompope 12 oz','',95),
('Para llevar','Chocolate con rompope 16 oz','',109),
('Para llevar','Chocoesspreso 12 oz','',95),
('Para llevar','Chocoespresso 16 oz','',109),
('Para llevar','Te 12 oz','',60),
('Para llevar','Te 16 oz','',72),
('Para llevar','Chai 12 oz','',82),
('Para llevar','Chai 16 oz','',89),
('Para llevar','Manzanilla chai de 12 oz','',82),
('Para llevar','Manzanilla chai de 16 oz','',89),
('Para llevar','Matcha de 12 oz','',82),
('Para llevar','Matcha de 16 oz','',89),
('Para llevar','Leche dorada de 12 oz','',82),
('Para llevar','Leche dorada de 16 oz','',89),
('Para llevar','Café dorado de 12 oz','',94),
('Para llevar','Café dorado de 16 oz','',104),
('Para llevar','Café mazapán de 12 oz','',94),
('Para llevar','Café mazapán de 16 oz','',106),
('Para llevar','Frappe de 12 oz','',80),
('Para llevar','Frappe de 16 oz','',90),
('Para llevar','Smoothie de 12 oz','',84),
('Para llevar','Smoothie de 16 oz','',92),
('Para llevar','Cambio de leche para llevar','',25),
('Paquetes Para Llevar','Pan + Capuccino/Latte 12 oz','',95),
('Paquetes Para Llevar','Pan + Americano 12 oz','',79),
('Paquetes Para Llevar','Pastel + Capuccino/Latte 12 oz','',131),
('Paquetes Para Llevar','Pastel + Americano 12 oz','',114),
('Paquetes Para Llevar','Bagel atún o jocoque + Capuccino/latte 12 oz','',152),
('Paquetes Para Llevar','Bagel atún o jocoque + Americano 12 oz','',137),
('Paquetes Para Llevar','Galletas + Capuccino/Latte 12 oz','',116),
('Paquetes Para Llevar','Galletas + Americano 12 oz','',99),
('Paquetes Para Llevar','Galletas + Té 12 oz','',116),
('Paquetes Para Llevar','Yogurt + Americano 12 oz','',99),
('Paquetes Para Llevar','Chapata + Capuccino/Latte 12 oz','',162),
('Paquetes Para Llevar','Chapata + Americano 12 oz','',149),
('Paquetes Para Llevar','Quiché + Capuccino/Latte de 12 oz','',159),
('Paquetes Para Llevar','Quiché + Americano de 12 oz','',144)

                `)
        } catch (err) {
            throw { satuts: 500 }
        }
    }
}


export default mInicio;